## Name: Samiksha Rajpal

## Student Id: 8908982

### Lab 8 - A Dot product and a Matrix Multiplication in PyTorch and Tensorflow

1. Setup Tensorflow and PyTorch based on the instructions in ./setup/README.md

  - Done


2. Using PyTorch:
- Calculate the dot product between two vectors each of length 3 (1.5 points)
- Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2) (1.5 points)

In [1]:
#part a : dot product of 2 vectors

# using pytorch

import torch

# Defining two vectors of length 3
vec1 = torch.tensor([2, 20, 95], dtype=torch.float32)
vec2 = torch.tensor([3, 30, 10], dtype=torch.float32)

# Calculatint the dot product
dotproduct = torch.dot(vec1, vec2)

print("Dot Product:", dotproduct.item())


Dot Product: 1556.0


In [2]:
# part b: matrix multipilication of 2 dimensional matrxi using pytorch

import torch

# Defining the two matrices
matA = torch.tensor([[2.0, 20.0], [22.0, 4.0]])
matB = torch.tensor([[3.0, 30.0], [10.0, 1.0]])

# Matrix multiplication
matC = torch.mm(matA, matB)


print("First Matrix:")
print(matA)

print("\nSecond Matrix:")
print(matB)

print("\nProduct Matrix C:")
print(matC)


First Matrix:
tensor([[ 2., 20.],
        [22.,  4.]])

Second Matrix:
tensor([[ 3., 30.],
        [10.,  1.]])

Product Matrix C:
tensor([[206.,  80.],
        [106., 664.]])
