## Name: Samiksha Rajpal

## Student Id: 8908982

### Lab 8 - A Dot product and a Matrix Multiplication in PyTorch and Tensorflow

1. Setup Tensorflow and PyTorch based on the instructions in ./setup/README.md

  - Done



3. Using Tensorflow:
- Calculate the dot product between the same vectors as above (re-define them in Tensorflow) (1.5 points)
- Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) (1.5 points)

In [1]:

# part a : dot product of two vectors using tensorflow

import tensorflow as tf

# Defining two vectors of length 3 as defined above for pytorch
vec1 = tf.constant([2, 20, 95], dtype=tf.float32)
vec2 = tf.constant([3, 30, 10], dtype=tf.float32)

# Calculating the dot product
dotproduct = tf.tensordot(vec1, vec2, axes=1)

print("Dot Product:", dotproduct.numpy())




Dot Product: 1556.0


2023-11-11 19:05:41.153548: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2 Pro
2023-11-11 19:05:41.153574: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2023-11-11 19:05:41.153582: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2023-11-11 19:05:41.153670: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-11-11 19:05:41.153735: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [2]:
# part b: matrix multipilication of 2 dimensional matrxi using tensorflow

import tensorflow as tf

# Defining the two matrices
matA = tf.constant([[2.0, 20.0], [22.0, 4.0]])
matB = tf.constant([[3.0, 30.0], [10.0, 1.0]])

# Matrix multiplication
matC = tf.matmul(matA, matB)

print("First Matrix:")
print(matA.numpy())

print("\nSecond Matrix:")
print(matB.numpy())

print("\nProduct Matrix C:")
print(matC.numpy())


First Matrix:
[[ 2. 20.]
 [22.  4.]]

Second Matrix:
[[ 3. 30.]
 [10.  1.]]

Product Matrix C:
[[206.  80.]
 [106. 664.]]
